### ISSUE TITLE
allow per-headline interleave pdf file association?

### ISSUE THREAD

**Issue by titaniumbones** [rudolfochrist/interleave-mode#13]
Hi! Interleave looks really cool. I keep all my notes in a single org-mode file. How hard would it be to allow INTERLEAVE_PDF to be set as a headline property, with page notes kept in subheadings? Does this seem possible?  
Many Thanks!

**Comment by rudolfochrist** [comment]
Hi @titaniumbones ,

I think this is definitely possible and I think it shouldn't be that hard. We should decide if the pdf exchange should happen implicitly (say, you go to a new heading with <kbd>n</kbd> and `interleave` recognizes a new pdf and switch to it behind the scenes) or explicitly (via a key binding for switching pdfs). Currently I favor the latter. 

What bothers me is, if you have many pdfs with a lot of pages. This _can_ lead to long waiting times while switching pdfs. But this is premature optimization. 

As I told you on the orgmode mailing list already, I'm currently shot on time;. Maybe I can look deeper into it the upcoming weekend. 

-Sebastian

**Comment by titaniumbones** [comment]
Hi Sebastian,

If you think it's not so hard, I would love to see it implemented. It
would make me much more likely to use interleave personally.  In any
caes, many thanks for considering it!
