### ISSUE TITLE
Allow page notes to contain sub-headings

### ISSUE THREAD

**Issue by kaushalmodi** [rudolfochrist/interleave-mode#24]
Currently, we cannot have 

```
* Notes for page N
** sub notes N.1
*** sub sub notes N.1.1
```

because of the use of `(org-narrow-to-subtree)` in commands like `interleave--sync-pdf-page-next` and `interleave--sync-pdf-page-previous`. 

Solving https://github.com/rudolfochrist/interleave/issues/23 should probably fix this issue too.

**Comment by rudolfochrist** [comment]
Resolved

**Comment by kaushalmodi** [comment]
Really appreciate your active development on this package. Thank you.
