### ISSUE TITLE
Interleave in second level headlines in multi-PDF notes

### ISSUE THREAD

**Issue by jmburgos** [rudolfochrist/interleave-mode#33]
Hello,
It seems that in multi-PDF notes files interleave only works if the :INTERLEAVE_PDF: property is set in a first-level headline.  Would it be possible to make it work also in second-level headlines?  The reason is that I use first-level headlines in my notes file to organize my notes, and the notes in each paper go in the second level.  Something like this:

* Papers in Some topic
** Smith2009
:PROPERTIES:
  :Custom_ID: Smith2009
  :INTERLEAVE_PDF: /path/to/my/pdfs/Smith2009.pdf
  :END:
** Jones2010
:PROPERTIES:
  :Custom_ID: Jones2010
  :INTERLEAVE_PDF: /path/to/my/pdfs/Jones2010.pdf
  :END:

... etc.

Many thanks!

**Comment by rudolfochrist** [comment]
Yes. This will happen when #23 is implemented (and therefore #24).

Best,
Sebastian

**Comment by jmburgos** [comment]
Ah, sorry, I missed these previous requests.  Thanks!.  When this gets done, the narrowing would still occur?  If so, could it be optional?  I find myself doing C-x n w all the time because when I write notes I want to see what notes I wrote on previous pages.

**Comment by rudolfochrist** [comment]
Hmm, yes. Narrowing would still occur. Making it optional needs some work but is definitely possible. 

Can we close this issue then?

**Comment by jmburgos** [comment]
Yes, thanks again.

**Comment by rudolfochrist** [comment]
Reopening because it's different from #24.

**Comment by rudolfochrist** [comment]
Resolved.
