### ISSUE TITLE
The obsolete functions are missing autoload cookies.

### ISSUE THREAD

**Issue by gdobbins** [rudolfochrist/interleave-mode#35]
With the recent deprecation of `interleave` for `interleave-mode` etc. there are now many uses of `define-obsolete-function-alias` but none have an `;;;##autoload` preceding them, meaning any users who are not aware of the change and rely on autoloading the package will suddenly find things do not work as expected and have no idea how to fix it. Autoload cookies should be placed as appropriate and then users will be given a message similar to

>‘interleave’ is an obsolete command (as of 1.3); use ‘interleave-mode’ instead.

when invoking `interleave` automatically.

**Comment by rudolfochrist** [comment]
Thank you very much. I fix this immediately.
