### ISSUE TITLE
Subtree is not correctly displayed when interleave-disable-narrowing is set to t

### ISSUE THREAD

**Issue by Yevgnen** [rudolfochrist/interleave-mode#41]
When `interleave-disable-narrowing` is set to `t`, the heading goes a bit strange when using `p` and `n` for paging in the pdf buffer.

Reproducing: Open the org file [here](https://gist.github.com/Yevgnen/57c26589040f51d7db524b10c5e4970f) with the minimal emacs config 
```
(package-initialize)
(require 'org)
(require 'interleave)
(setq interleave-disable-narrowing t)
```
Save the pdf [file](https://arxiv.org/pdf/1402.3722v1.pdf) to the path specified by the first heading. `M-x interleave-mode` in the org buffer at the first level heading `2014 - Word2vec Explained: Deriving Mikolov Et Al.’s Negative-Sampling Word-Embedding Method`, then the window is switched to the pdf buffer. Use `p` and `n` to navigate, and the org subtree is expanded with strange display.

<img width="1392" alt="screen shot 2016-12-13 at 6 15 47 pm" src="https://cloud.githubusercontent.com/assets/16749790/21136517/e5fbba4a-c160-11e6-8b30-8bb34c7e034e.png">
<img width="1392" alt="screen shot 2016-12-13 at 6 15 53 pm" src="https://cloud.githubusercontent.com/assets/16749790/21136522/e76c76a8-c160-11e6-8f96-6304e1691d98.png">

As we can see, the level 2 heading `** Notes for page 2` went to the first line.

<img width="1392" alt="screen shot 2016-12-13 at 6 16 20 pm" src="https://cloud.githubusercontent.com/assets/16749790/21136554/0e65b530-c161-11e6-9aee-6b86e6a93214.png">

If quit `interleave-mode`, and use `org-narrow-to-subtree` to narrow to subtree, everything goes fine.

Emacs version: `GNU Emacs 25.1.1 (x86_64-apple-darwin16.1.0, Carbon Version 157 AppKit 1504.6) of 2016-12-12`

Org version: `Org mode version 9.0.1 (9.0.1-elpa @ /Users/user/.emacs.d/elpa/org-20161118/)`

**Comment by rudolfochrist** [comment]
Thank you for the detailed bug report. I'm going to fix this over the holidays.
