### ISSUE TITLE
Open/create .org notes file when launching interleave from a pdf [Feature/TODO?]

### ISSUE THREAD

**Issue by kaushalmodi** [rudolfochrist/interleave-mode#5]
Hi,

I have this idea:
- Set a `defvar` called `interleave--notes-dir`. The user should make a point to save the pdf associated notes org file either in the same folder or in the `interleave--notes-dir`.
- When calling `M-x interleave` from a pdf file (let's say `file-name.pdf`), we will search for `file-name.org` first in the same folder and then in `interleave--notes-dir`. If the search is successful, that file is opened and the Interleave session will continue as now.
- But if `file-name.org` is not found, then it is created in `interleave--notes-dir` with the header `#+INTERLEAVE_PDF: /path/to/file-name.pdf`. The user can choose to move it to the same folder as the pdf is they wish (or we can add a `defvar` for an option to create the notes org in either the same folder or in `interleave--notes-dir` by default). _I personally like the idea of keeping all notes in one folder._ And then the Interleave session will continue as now.

What do you think? I will get started on adding this feature when I get a chance.

**Comment by rudolfochrist** [comment]
Sounds good. That doesn't quite fit my own personal workflow, but go for it. If you come up with a PR, I'll merge it.

**Comment by rudolfochrist** [comment]
whoops
