### ISSUE TITLE
Can interleave work with Hyperbole outline files (.kotl)?

### ISSUE THREAD

**Issue by ghost** [rudolfochrist/interleave-mode#51]
Recently started looking at this file format and find the outlining feature very interesting. Document is mad of nodes/cells, which have an absolute and relative ID, can be reordered and automatically renumbered, moved about etc. Would love to see the two combined, but must admit I can't see how meta data is embedded in these type of files (I understand they're hidden, unlike org's drawers).

**Comment by rudolfochrist** [comment]
Hi @usharf,

`interleave` will not work out of the box with Hyperbole files. Since I'm not a Hyperbole user myself, I have no idea how hard it is to bring `interleave` to work with Hyperbole outline files. 

If you want it to give it a try this would be an interesting PR :)

**Comment by ghost** [comment]
I would look into it while learning to use Hyperbole :)
