### ISSUE TITLE
Controlling window in focus

### ISSUE THREAD

**Issue by ghost** [rudolfochrist/interleave-mode#53]
I know I can always type "i" to go to the editing buffer, but the instinct is to start typing right away, but is it possible to keep the editing window in focus, rather than jump to the PDF every time I move forward/backwards (Alt-n/p)? 

Pressing "i" will create a new sub-heading per page, which is not what I need most of time. I prefer to create an annotation documents that mirrors the structure of PDF I'm working on.

**Comment by rudolfochrist** [comment]
Hi @usharf,

> I know I can always type "i" to go to the editing buffer, but the instinct is to start typing right away, but is it possible to keep the editing window in focus, rather than jump to the PDF every time I move forward/backwards (Alt-n/p)?

Currently it is not possible to navigate the PDF from the notes buffer. <kbd>M-p</kbd> and <kbd>M-n</kbd> do, is to jump to the previous or next *set* of notes. This is, say, you have some notes for page 3 and then you add some notes for page 15. When you then press <kbd>M-p</kbd> `interleave` will got page 3 and display the notes for that page. 

> Pressing "i" will create a new sub-heading per page, which is not what I need most of time. I prefer to create an annotation documents that mirrors the structure of PDF I'm working on.

If this is your workflow, then I'm afraid `interleave` isn't the right tool for that. It doesn't really care for the PDF content structure, it just creates a 1:1 mapping of PDF pages to notes. I think for your case your better using a normal `doc-view`/`pdf-tools` buffer besides a `org-mode` buffer and, perhaps, create some custom key bindings to navigate the PDF.

**Comment by ghost** [comment]
Thanks for the explanation. It is a very useful tool, regardless. To be honest, most of the time I do work with PDFs which don't have an outline (scanned), so it'd not have been possible in any case.

But when the PDF does have an outline, I thought it should be able to support such a feature, using `pdf-tools` introspection features (I didn't look there yet to see if it's really so simple).

Browsing the org document with `Alt-n` and `Alt-p` does works as is even when two top-level headings in the notes file, have the `interleave_page_note` property set to the same page number (i.e. if the break down of two consecutive headings happen to be on the same "page" in the PDF).
