### ISSUE TITLE
Magic comment not working for Emacs 27

### ISSUE THREAD

**Issue by zw963** [rudolfochrist/interleave-mode#61]
It always try to insert a new comment when open `interleave-mode`, following is a gif, thank you.

![Peek 2020-03-07 14-12](https://user-images.githubusercontent.com/549126/76137972-b1e56200-607d-11ea-9d04-5291309d681f.gif)

**Comment by rudolfochrist** [comment]
Sorry to here that. Further this won't be fixed anytime soon (if you would like to send a PR, please fee lfree to do so). This project is basically dead. I should archive it and add a note to the readme. 
May I suggest that you give [weirdNox/org-noter](https://github.com/weirdNox/org-noter) a try. It does basically the same, but is actively maintained. 

/cc @weirdNox

**Comment by zw963** [comment]
Thank you, i will check that package.
