### ISSUE TITLE
Add unmaintained note to interleave.el "Commentary" section

### ISSUE THREAD

**Issue by skangas** [rudolfochrist/interleave-mode#64]
As I was looking into using either this or `org-noter`, it would have been helpful to know this package is currently unmaintained. May I suggest to perhaps a note to this effect to the "Commentary" section so this is visible from within Emacs itself (i.e. `M-x list-packages`)?

Thanks for the package.

**Comment by rudolfochrist** [comment]
I guess it's the best to remove it from melpa entirely. If someone still wants to use interleave for whatever reason, she can install it manually.

**Comment by rudolfochrist** [comment]
see melpa/melpa#7527
